POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Tyä miähen plogi 3",
  "author": "Kauppisen Pete",
  "url": "www.kauppisenmaansiirtofirma.fi/kolmas-bloki",
  "likes": "3"
}