POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJyaXRuZXkiLCJpZCI6IjVmYjUzNWRjNzJiMTljNjJhMDVjMGU1MiIsImlhdCI6MTYwNTcxMTYzNn0.FfrOfvazG05kj2zj3OERX8RqQQ0Ro7AJ43Fq6ncBlVo

{
  "title": "City Hipster Daydreams",
  "author": "Kendra Miller",
  "url": "www.bosslady.com"
}